services:
  bff:
    environment:
      GRAPHIQL_ENABLED: true

  postgres:
    ports:
      - "5432:5432"

  sftp:
    ports:
      - "2222:22"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"