services:

  frontend:
    build:
      context: .
      dockerfile: sample-frontend/Dockerfile
      args:
        VITE_GRAPHQL_ENDPOINT: http://localhost:8082/graphql
        VITE_BFF_BASIC_AUTH_USERNAME: ${VITE_BFF_BASIC_AUTH_USERNAME}
        VITE_BFF_BASIC_AUTH_PASSWORD: ${VITE_BFF_BASIC_AUTH_PASSWORD}
    ports:
      - "3000:80"
    depends_on:
      - bff

  app:
    build:
      context: .
      dockerfile: sample-backend/Dockerfile
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: ${SAMPLE_BACKEND_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  bff:
    build:
      context: .
      dockerfile: sample-bff/Dockerfile
    ports:
      - "8082:8082"
    environment:
      BACKEND_BASE_URL: http://app:8080
      BFF_SECURITY_USER_NAME: ${BFF_SECURITY_USER_NAME}
      BFF_SECURITY_USER_PASSWORD: ${BFF_SECURITY_USER_PASSWORD}
    depends_on:
      - app

  batch:
    build:
      context: .
      dockerfile: sample-batch/Dockerfile
    profiles:
      - batch
    environment:
      BACKEND_BASE_URL: http://app:8080
      SPRING_DATASOURCE_URL: ${SAMPLE_BATCH_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SFTP_HOST: sftp
      SFTP_PORT: 22
      SFTP_USERNAME: ${SFTP_USERNAME}
      SFTP_PASSWORD: ${SFTP_PASSWORD}
      SFTP_REMOTE_DIRECTORY: ${SFTP_REMOTE_DIRECTORY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REPORT_QUEUE_NAME: user-name-list-report.request
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      - app
      - postgres
      - sftp
      - rabbitmq
    volumes:
      - ./sample-batch/work/output:/app/work/output

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  sftp:
    image: atmoz/sftp:latest
    ports:
      - "2222:22"
    command: ${SFTP_USERNAME}:${SFTP_PASSWORD}:1001
    volumes:
      - ./docker/sftp/upload:/home/${SFTP_USERNAME}/upload

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  rabbitmq-data: