services:
  bff:
    ports:
      - "8082:8082"
    environment:
      GRAPHIQL_ENABLED: true
      BFF_CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173

  postgres:
    ports:
      - "5432:5432"

  sftp:
    ports:
      - "2222:22"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"